import { FilterType } from './_type'
import {
  Cpu,
  FerrisWheel,
  Handshake,
  HeartPulse,
  Microscope,
  Newspaper,
  Trophy,
} from 'lucide-react'

export const DEFAULT_CATEGORIES: FilterType[] = [
  {
    icon: Newspaper,
    label: 'General',
    include: false,
    exclude: false,
  },
  {
    icon: Handshake,
    label: 'Business',
    include: false,
    exclude: false,
  },
  {
    icon: FerrisWheel,
    label: 'Entertainment',
    include: false,
    exclude: false,
  },
  {
    icon: HeartPulse,
    label: 'Health',
    include: false,
    exclude: false,
  },
  {
    icon: Microscope,
    label: 'Science',
    include: false,
    exclude: false,
  },
  {
    icon: Trophy,
    label: 'Sports',
    include: false,
    exclude: false,
  },
  {
    icon: Cpu,
    label: 'Technology',
    include: false,
    exclude: false,
  },
]

export const DEFAULT_COUNTRIES: FilterType[] = [
  { label: 'Argentina', icon: 'ar', include: null, exclude: null },
  { label: 'Australia', icon: 'au', include: null, exclude: null },
  { label: 'Austria', icon: 'at', include: null, exclude: null },
  { label: 'Belgium', icon: 'be', include: null, exclude: null },
  { label: 'Brazil', icon: 'br', include: null, exclude: null },
  { label: 'Bulgaria', icon: 'bg', include: null, exclude: null },
  { label: 'Canada', icon: 'ca', include: null, exclude: null },
  { label: 'China', icon: 'cn', include: null, exclude: null },
  { label: 'Colombia', icon: 'co', include: null, exclude: null },
  { label: 'Czech Republic', icon: 'cz', include: null, exclude: null },
  { label: 'Egypt', icon: 'eg', include: null, exclude: null },
  { label: 'France', icon: 'fr', include: null, exclude: null },
  { label: 'Germany', icon: 'de', include: null, exclude: null },
  { label: 'Greece', icon: 'gr', include: null, exclude: null },
  { label: 'Hong Kong', icon: 'hk', include: null, exclude: null },
  { label: 'Hungary', icon: 'hu', include: null, exclude: null },
  { label: 'India', icon: 'in', include: null, exclude: null },
  { label: 'Indonesia', icon: 'id', include: null, exclude: null },
  { label: 'Ireland', icon: 'ie', include: null, exclude: null },
  { label: 'Israel', icon: 'il', include: null, exclude: null },
  { label: 'Italy', icon: 'it', include: null, exclude: null },
  { label: 'Japan', icon: 'jp', include: null, exclude: null },
  { label: 'Latvia', icon: 'lv', include: null, exclude: null },
  { label: 'Lithuania', icon: 'lt', include: null, exclude: null },
  { label: 'Malaysia', icon: 'my', include: null, exclude: null },
  { label: 'Mexico', icon: 'mx', include: null, exclude: null },
  { label: 'Morocco', icon: 'ma', include: null, exclude: null },
  { label: 'Netherlands', icon: 'nl', include: null, exclude: null },
  { label: 'New Zealand', icon: 'nz', include: null, exclude: null },
  { label: 'Nigeria', icon: 'ng', include: null, exclude: null },
  { label: 'Norway', icon: 'no', include: null, exclude: null },
  { label: 'Philippines', icon: 'ph', include: null, exclude: null },
  { label: 'Poland', icon: 'pl', include: null, exclude: null },
  { label: 'Portugal', icon: 'pt', include: null, exclude: null },
  { label: 'Romania', icon: 'ro', include: null, exclude: null },
  { label: 'Saudi Arabia', icon: 'sa', include: null, exclude: null },
  { label: 'Serbia', icon: 'rs', include: null, exclude: null },
  { label: 'Singapore', icon: 'sg', include: null, exclude: null },
  { label: 'Slovakia', icon: 'sk', include: null, exclude: null },
  { label: 'Slovenia', icon: 'si', include: null, exclude: null },
  { label: 'South Africa', icon: 'za', include: null, exclude: null },
  { label: 'South Korea', icon: 'kr', include: null, exclude: null },
  { label: 'Sweden', icon: 'se', include: null, exclude: null },
  { label: 'Switzerland', icon: 'ch', include: null, exclude: null },
  { label: 'Taiwan', icon: 'tw', include: null, exclude: null },
  { label: 'Thailand', icon: 'th', include: null, exclude: null },
  { label: 'Turkey', icon: 'tr', include: null, exclude: null },
  { label: 'UAE', icon: 'ae', include: null, exclude: null },
  { label: 'Ukraine', icon: 'ua', include: null, exclude: null },
  { label: 'United Kingdom', icon: 'gb', include: null, exclude: null },
  { label: 'United States', icon: 'us', include: null, exclude: null },
  { label: 'Venezuela', icon: 've', include: null, exclude: null },
]

export const DEFAULT_LANGUAGES: FilterType[] = [
  { label: 'English', icon: 'uk', include: null, exclude: null },
  { label: 'Arabic', icon: 'sa', include: null, exclude: null },
  { label: 'Bengali', icon: 'bd', include: null, exclude: null },
  { label: 'Bulgarian', icon: 'bg', include: null, exclude: null },
  {
    label: 'Chinese (Simplified and Traditional)',
    icon: 'cn',
    include: false,
    exclude: false,
  },
  { label: 'Croatian', icon: 'hr', include: null, exclude: null },
  { label: 'Czech', icon: 'cz', include: null, exclude: null },
  { label: 'Danish', icon: 'dk', include: null, exclude: null },
  { label: 'Estonian', icon: 'ee', include: null, exclude: null },
  { label: 'Finnish', icon: 'fi', include: null, exclude: null },
  { label: 'French', icon: 'fr', include: null, exclude: null },
  { label: 'Greek', icon: 'gr', include: null, exclude: null },
  { label: 'Gujarati', icon: 'in', include: null, exclude: null },
  { label: 'Hebrew', icon: 'il', include: null, exclude: null },
  { label: 'Hindi', icon: 'in', include: null, exclude: null },
  { label: 'Indonesian', icon: 'id', include: null, exclude: null },
  { label: 'Japanese', icon: 'jp', include: null, exclude: null },
  { label: 'Kannada', icon: 'in', include: null, exclude: null },
  { label: 'Korean', icon: 'kr', include: null, exclude: null },
  { label: 'Lithuanian', icon: 'lt', include: null, exclude: null },
  { label: 'Latvian', icon: 'lv', include: null, exclude: null },
  { label: 'Malayalam', icon: 'in', include: null, exclude: null },
  { label: 'Marathi', icon: 'in', include: null, exclude: null },
  { label: 'Dutch', icon: 'nl', include: null, exclude: null },
  { label: 'German', icon: 'de', include: null, exclude: null },
  { label: 'Norwegian', icon: 'no', include: null, exclude: null },
  { label: 'Persian', icon: 'ir', include: null, exclude: null },
  { label: 'Polish', icon: 'pl', include: null, exclude: null },
  { label: 'Portuguese', icon: 'pt', include: null, exclude: null },
  { label: 'Russian', icon: 'ru', include: null, exclude: null },
  { label: 'Romanian', icon: 'ro', include: null, exclude: null },
  { label: 'Serbian', icon: 'rs', include: null, exclude: null },
  { label: 'Slovak', icon: 'sk', include: null, exclude: null },
  { label: 'Slovenian', icon: 'si', include: null, exclude: null },
  { label: 'Swahili', icon: 'ke', include: null, exclude: null },
  { label: 'Swedish', icon: 'se', include: null, exclude: null },
  { label: 'Thai', icon: 'th', include: null, exclude: null },
  { label: 'Tamil', icon: 'in', include: null, exclude: null },
  { label: 'Telugu', icon: 'in', include: null, exclude: null },
  { label: 'Turkish', icon: 'tr', include: null, exclude: null },
  { label: 'Ukrainian', icon: 'ua', include: null, exclude: null },
  { label: 'Urdu', icon: 'pk', include: null, exclude: null },
  { label: 'Hungarian', icon: 'hu', include: null, exclude: null },
  { label: 'Vietnamese', icon: 'vn', include: null, exclude: null },
  { label: 'Italian', icon: 'it', include: null, exclude: null },
]

export const DEFAULT_SOURCES: FilterType[] = [
  { label: 'Google News', icon: 'google', include: null, exclude: null },
  { label: 'BBC News', icon: 'bbc', include: null, exclude: null },
  { label: 'CNN News', icon: 'cnn', include: null, exclude: null },
]
